### PR TITLE
[droid] Stop capturing when opening another camera. JB#56142

### PR DESCRIPTION
**Pull request by d-grigorev**
Camera HAL may reject connection to the camera if there's another camera
in locked state. This commit will do stopCapture() for currently running
camera if another camera instance is open.

### CODE REVIEW

**Comment by adenexter** [comment]
Can you make that per camera device? It should be possible to run a front and back camera at the same time.

**Comment by d-grigorev** [comment]
> It should be possible to run a front and back camera at the same time.
I'll try that. If I do this per-camera, some sites may keep multiple devices running, and that may slow down the device.

**Comment by adenexter** [comment]
> I'll try that. If I do this per-camera, some sites may keep multiple cameras running, and that may slow down the device.

If a site intentionally has multiple cameras running that is to be expected. 

Going back and re-reading the bug, I'm less convinced we should be doing anything. If a site starts a camera and doesn't stop it before creating a new object and starting that in the hope that the garbage collector will have kicked in in the meantime, then that's a bug in the site.

**Comment by d-grigorev** [comment]
> It should be possible to run a front and back camera at the same time.

I tried to open both cameras at the same time, it doesn't work. Low-end Mediatek devices lacks multicamera support, however higher SoC should work. I'm working on a flexible solution.

> Going back and re-reading the bug, I'm less convinced we should be doing anything. If a site starts a camera and doesn't stop it before creating a new object and starting that in the hope that the garbage collector will have kicked in in the meantime, then that's a bug in the site.

It completely breaks the possibility of using the camera on such sites. I've seen this behavior on a couple of video conferencing sites, and now the newer version of janus demo does the same. It looks like we have to adapt somehow.

**Comment by d-grigorev** [comment]
In the latest version of the commit, I first try to open the camera without closing all other devices.

**Comment by d-grigorev** [comment]
Changed the signature of `DroidCamera::create()` and the commit message.

**Review by okodron — APPROVED** [review]
LGTM now

**Review by adenexter — APPROVED** [review]

**Pull request merged**
